### ISSUE TITLE
Rewrite build config parsing to me shorter, cleaner and use some standard config format

### ISSUE THREAD

**Issue by igor-petruk** [igor-petruk/scriptisto#1]
YAML or TOML are good candidates

**Comment by igor-petruk** [comment]
Something like this if TOML

```toml
script_src="script.ml"
build_cmd="dune build script.exe"
target_bin="@@@/_build/default/script.exe"

[[file]]
name="dune"
contents=""""
(executable
     (name script)
      (libraries lwt.unix))"""
```

Inside of the block

```python
#  scriptisto-begin
#  <-- here
#  scriptisto-end
