### ISSUE TITLE
[Feature Request]: adding a config file to avoid boilerplate

### ISSUE THREAD

**Issue by AlejandroSuero** [igor-petruk/scriptisto#53]
## Feature request

Wouldn't it be better for the UX to parse a, for example, `YAML` file located in, for example, `$XDG_CONFIG/scriptisto/config.yml` or loading a `YAML` file for a variable like `$SCRIPTISTO_CONFIG`, and if not found or defined, use the current way of defining the per-script `build_cmd`.

## Proposal

```yml
# path/to/config.yml
lang: "c"
  build_cmd: "clang -O2 {{ script_src }} `pkg-config --libs --cflags glib-2.0`"
lang: "go
  build_cmd: "go build {{ script_src }}"
```

> [!NOTE]
>
> I will use `TOML` since it differentiates more the blocks like:
>
> ```toml
> [c]
> build_cmd = "clang -O2 [$script_src] `pkg-config --libs --cflags glib-2.0`"
> ```

When parsing it take the `script.{c,go}`, substitute it with the `script_src` (current file from the she-bang call) and add it to `build_cmd` like `-o ./script`

> [!NOTE]
>
> I am not a Rust developer, so I don't know how complicated or not it is this environment, but [starship](https://starship.rs) does it to configure the prompt.

If the current way of doing things is present on the current `script.{c,go}` use that instead of `config.yml` so it has a way to change per-script for some corner cases.
